global:
  imageRepositoryPath: epiphanyplatform/
  imageVersion: master
  imagePullPolicy: Always
  kafkaBrokers: 10.1.5.4:9092
  rabbitMqConnectionString: "{{BTR_RMQ_SCHEMA}}://{{BTR_RMQ_USER}}:{{BTR_RMQ_PASSWORD}}@{{ hostvars[groups['rabbitmq'][0]]['ansible_host'] }}:{{BTR_RMQ_PORT}}/{{BTR_RMQ_VHOST}}"
  cdlImagePullSecrets: services
  reportTopic: cdl.errors

dataRouter:
  inputQueue: cdl.data.input
  image: cdl-data-router
  bin: data-router

schemaRegistry:
  storageClass: standard
  storageSize: 3Gi
  port: 30150
  image: cdl-schema-registry
  bin: schema-registry

leaderElector:
  heartbeatTime: 2
  image: cdl-leader-elector
  bin: leader-elector

commandService:
  image: cld-command-service
  bin: command-service

documentStorage:
  image: cdl-document-storage
  bin: document-storage

postgres-document:
  commandServiceReplicaCount: 1
  postgresDbReplicaCount: 0
  postgresConnectionString: "postgres://{{BTR_PG_USER}}:{{BTR_PG_PASSWORD}}@{{ hostvars[groups['postgresql'][0]]['ansible_host'] }}/{{BTR_PG_DBNAME}}:5432"
  inputTopic: cdl.document.data

sled-document:
  replicaCommandCount: 0
  replicaDbCount: 0
  maxDbSize: 3Gi
  storageClass: azurefile
  inputTopic: cdl.document2.data

druid-timeseries:
  replicaCommandCount: 1
  inputTopic: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
