global:
  imageRepositoryPath: epiphanyservices.azurecr.io/
  imageVersion: 0.0.5
  imagePullPolicy: Always
  kafkaBrokers: 10.1.5.4:9092
  rabbitMqConnectionString: "amqp://rabbitmq:rabbitmq@10.1.1.4:5672/%2f"
  cdlImagePullSecrets: services
  reportTopic: cdl.errors

dataRouter:
  inputQueue: cdl.data.input

schemaRegistry:
  storageClass: standard
  storageSize: 3Gi
  port: 30150

leaderElector:
  heartbeatTime: 2

postgres-document:
  commandServiceReplicaCount: 1
  postgresDbReplicaCount: 0
  postgresConnectionString: "postgres://postgres:postgres@10.1.1.5/cdldb"
  inputTopic: cdl.document.data

sled-document:
  replicaCommandCount: 1
  replicaDbCount: 1
  maxDbSize: 3Gi
  storageClass: azurefile
  inputTopic: cdl.document2.data

druid-timeseries:
  replicaCommandCount: 1
  inputTopic: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
